name: Test

on:
  workflow_dispatch:

jobs:
  dart_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: pub get
        run: dart pub get
      - name: check
        run: dart run lib/uptodate.dart
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
