name: Test

on:
  workflow_dispatch:

jobs:
  dart_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart pub run build_runner build --delete-conflicting-outputs
      - run: dart test
      - run: dart run lib/uptodate.dart
